/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dns_demo_TestDnsResolve */

#ifndef _Included_com_dns_demo_TestDnsResolve
#define _Included_com_dns_demo_TestDnsResolve
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dns_demo_TestDnsResolve
 * Method:    resolveDns
 * Signature: (Ljava/lang/String;Lcom/dns/demo/DnsCallback;)V
 */
JNIEXPORT void JNICALL Java_com_dns_demo_TestDnsResolve_resolveDns
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
